movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>',views.detail,name='detail')
]

vidrental/urls.py
from django.contrib import admin
from django.urls import path,include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path('',views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))  
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()     
        resource_name = 'movies'
        excludes = ['date_created']
        

        
        

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Movie


def index(request):
    movies = Movie.objects.all()
    return render(request,'movies/index.html',{ 'movies': movies })
    
def detail(request, movie_id):
        movie = get_object_or_404(Movie, pk=movie_id)
        return render(request, 'movies/detail.html', {'movie': movie})
        

    

vidrental/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %} 
{% block content %}
<dl>
    <dt>Title</td>
    <dd>{{ movie.title }}</dd>
    <dt>Genre</td>
    <dd>{{ movie.genre }}</dd>
    <dt>Stock</td>
    <dd>{{ movie.number_in_stock }}</dd>    
</dl>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %} 
{% block content %}
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Stock</th>
      <th>Daily Rate</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies%}
    <tr>
      <td><a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a></td>
      <td>{{ movie.genre }}</td>
      <td>{{ movie.number_in_stock }}</td>
      <td>{{ movie.daily_rate }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Video Rental</title>

    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
      integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu"
      crossorigin="anonymous"
    />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">
              <img alt="" src="...">Video Rental
            </a>
          </div>
        </div>
      </nav>
      <main class="container">
    {% block content %}
    {% endblock %}
      </main>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script
      src="https://code.jquery.com/jquery-1.12.4.min.js"
      integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
      crossorigin="anonymous"
    ></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
      integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content%}
    <a href ="{% url 'movies:index' %}">Movies</a>
{% endblock %}